### ISSUE TITLE
Allow choosing between named and positional parameters

### ISSUE THREAD

**Issue by tomwyr** [tomwyr/union#2]
- Allow per annotation configuration

**Comment by yoodame** [comment]
I noticed the named params are rather long considering the length on the class. What are thoughts on allowing custom param names?

Instead of:
```
@Union.of([
  Fragment_Order__CrescentSaveOrder,
])
```

You could pass the following where the first element is the custom name?
```
@Union.of([
  [shortName, Fragment_OrderTargetWaypoint__TransferMethodOrderWaypoint],
  Fragment_Order__CrescentSaveOrder
])
```

or 

```
@Union.of([
  @Name('shortName') Fragment_OrderTargetWaypoint__TransferMethodOrderWaypoint,
  Fragment_Order__CrescentSaveOrder
])
```

**Comment by tomwyr** [comment]
Cool idea, thanks for the suggestion. To extend it a little bit, I'm thinking about an additional config class that could be expanded without introducing breaking changes in the future:
```Dart
class UnionCase {
  Type type
  String? name
  // ... other config options
}
```
On the annotations side there could be:
```Dart
@Union.ofTypes([
  MuchTooLongTypeA,
  TypeB,
])

@Union.of([
  UnionCase(MuchTooLongTypeA, name: 'typeA')
  UnionCase(TypeB)
])
```

**Comment by yoodame** [comment]
Solid!!

**Comment by yoodame** [comment]
@tomwyr  as part of this feature, could we support generating getters for each name?

```
extension TransferTargetExtension on TransferTarget {
  FinancialAccount get asFinancialAccount {
    return _as<FinancialAccount>();
  }

  PaymentMethod get asPaymentMethod {
    return _as<PaymentMethod>();
  }

  T _as<T>() {
    if (this is T) {
      return this as T;
    }
    throw UnsupportedError(
        'The TransferTarget instance is not of type ${T.toString()}');
  }
}```

**Comment by tomwyr** [comment]
@yoodame I can add `as` getters but it would be easier to implement as a separate feature. Created #6.

**Comment by tomwyr** [comment]
Added #7 and #8 to split the work into smaller pieces.
